### ISSUE TITLE
开始时间取值错误，导致统计时常错误

### ISSUE THREAD

**Issue by cookily** [ucloud/urtc-js-demo#1]
房间名称 | 开始时间 | 结束时间 | 时长 | 累计总用户数 | 峰值用户数 | 当前用户数
-- | -- | -- | -- | -- | -- | --
1 | 2019-10-10 00:00:00 | 2019-10-10 10:54:51 | 10h 54min 51s

**Comment by wendy-shi-19** [comment]
新的SDK已经修复此问题！
请取新的SDK使用。
https://docs.ucloud.cn/video/urtc/sdk/web
