### ISSUE TITLE
有人维护吗？

### ISSUE THREAD

**Issue by Davidzhu001** [ucloud/urtc-js-demo#2]
TypeError: Cannot read property 'userName' of null
![image](https://user-images.githubusercontent.com/9436230/74235547-3a384780-4d0a-11ea-8cd4-978817d73dcb.png)

**Comment by zhangjizhe** [comment]
> TypeError: Cannot read property 'userName' of null
> ![image](https://user-images.githubusercontent.com/9436230/74235547-3a384780-4d0a-11ea-8cd4-978817d73dcb.png)

本周内会更新版本，更新后会解决，

**Comment by zhangjizhe** [comment]
> TypeError: Cannot read property 'userName' of null
> ![image](https://user-images.githubusercontent.com/9436230/74235547-3a384780-4d0a-11ea-8cd4-978817d73dcb.png)

已经发布新版本，请更新重启动试试。本地测试可以
